### 1. You are given two strings s and t. String t is generated by randomly shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.

In [17]:
import logging

In [18]:
logging.basicConfig(filename = 'test.log', level = logging.DEBUG, format = '%(message)s %(error)s')

In [22]:

class fd:
    """Class to find difference"""
    def __init__(self,first,second):
        try:
            self.first = first
            self.second = second
            if (type(self.first) != str) and (type(self.second) != str):
                raise Exception("Error raised")
        except Exception as e:
            print(e)
            logging.error(e)
            
    def find_the_difference(self):
        """Class object to find difference between words"""
        try:
            a = set(self.first)
            b = set(self.second)
            to_return = list(a.symmetric_difference(b))
            return " ".join(to_return)
        except Exception as e:
            print(e)

In [23]:
a = fd('abcd','abcde')

In [24]:
a.find_the_difference()

'e'

In [25]:
a = fd("","y")

In [26]:
a.find_the_difference()

'y'

In [30]:
a = fd('ae','aea')

In [31]:
a.find_the_difference()

''

### 2. Given a function that accepts unlimited arguments, check and count how many data types are in those arguments. Finally return the total in a list.

In [16]:
def count_datatypes(*args):
    """Function to output data types"""
    try:
        main = [i for i in args]
        integers,string,boolean,lists,tuples,dics = 0,0,0,0,0,0
        for i in main:
            if type(i) == int:
                integers += 1
            if type(i) == str:
                string += 1
            if type(i) == bool:
                
                boolean += 1
            if type(i) == list:
                lists += 1
            if type(i) == tuple:
                tuples += 1
            if type(i) == dict:
                dics += 1
        return [integers,string,boolean,lists,tuples,dics]
    except Exception as  e:
        print(e)
        logging.error("Error outptu")

In [17]:
count_datatypes(1, 45, "Hi",
               True)

[2, 1, 1, 0, 0, 0]

In [18]:
count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23)

[2, 2, 3, 1, 0, 2]

In [20]:
count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6])

[2, 0, 1, 2, 2, 0]

### 3. A Fibonacci string is a precedence of the Fibonacci series. It works with any two characters of the English alphabet (as opposed to the numbers 0 and 1 in the Fibonacci series) as the initial items and concatenates them together as it progresses in a similar fashion as the Fibonacci series.

In [60]:
def fibo(till,words):
    """Prog for fibo"""
    try:
        main = ""
        if type(words)  != list:
            raise Exception("Invalid input")
        for i in range(len(words)-1):
            a,b = words[i],words[i+1]
        
        for i in range(till):
            to_add = "{} ".format(a)
            a,b = b,a+b
            main += to_add
        return main
    except Exception as e:
        print(e)
        logging.error(e)

In [61]:
fibo(3,['j','h'])

'j h jh '

In [62]:
fibo(5,['e','a'])

'e a ea aea eaaea '

In [63]:
fibo(6,['n','k'])

'n k nk knk nkknk knknkknk '

### 4. Given an integer between 0 and 26, make a variable (self.answer). That variable would be assigned to a string in this format:"nines:your answer, threes:your answer, ones:your answer" You need to find out how many ones, threes, and nines it would at least take for the number of each to add up to the given integer when multiplied by one, three or nine (depends).

In [80]:
def one_three_nines(number):
    """Prog"""
    try:
        a = number//9
        nines = number%9
        
        b = nines//3
        threes = nines%3
        
        ones = threes//1
        return "Nines:{}, Threes:{}, Ones:{}".format(a,b,ones)
    except Exception as e:
        print(e)
        logging.error(e)

In [81]:
one_three_nines(15)

'Nines:1, Threes:2, Ones:0'

In [82]:
one_three_nines(10)

'Nines:1, Threes:0, Ones:1'

In [83]:
one_three_nines(22)

'Nines:2, Threes:1, Ones:1'

### 5. The Fibonacci sequence is a classic use case for recursive functions since the value of the sequence at a given index is dependent on the sum of the last two values. However, the recursion tree created by solving the Fibonacci sequence recursively can grow quite fast. Therefore it can be important to think about the implications of running a function recursively. Depending on the size of n needed and the capabilities of the system in question you might want to take a different approach.

In [86]:
def fibo(n):
    a,b = 0,1
    for i in range(n+1):
        print(a)
        a,b = b,a+b
        if a >= n + 5:
            break

In [87]:
fibo(6)

0
1
1
2
3
5
8